# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Franz Flasch

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: personal techblog

description: Random tech stuff I want to document and share.
author:
  name: Franz Flasch
  email: franz.flasch@gmx.at
  github: franzflasch
  twitter: franzflasch86
  linkedin: www.linkedin.com/in/franz-flasch-0bb197157
  bio: Random tech stuff I want to document and share.
  email_md5: e1d4d58ebf1ed9d6ad5082e2cf788df5

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
